In [22]:
import pandas as pd

In [23]:
excel_file = "./smallruminants/AHLE scenario parameters SMALLRUMINANTS.xlsx"

df = pd.read_excel(excel_file)
df.head(10)

,AHLE Parameter,Notes,CLM_S_Current,CLM_S_Ideal,CLM_S_all_mortality_zero,CLM_S_all_mort_25_imp,CLM_S_all_mort_50_imp,CLM_S_all_mort_75_imp,CLM_S_mortality_zero_N,CLM_S_mortality_zero_J,...,Past_S_Current_growth_75_imp_All,Past_S_Current_growth_100_imp_All,CLM_G_Current_growth_25_imp_All,CLM_G_Current_growth_50_imp_All,CLM_G_Current_growth_75_imp_All,CLM_G_Current_growth_100_imp_All,CLM_S_Current_growth_25_imp_All,CLM_S_Current_growth_50_imp_All,CLM_S_Current_growth_75_imp_All,CLM_S_Current_growth_100_imp_All
0,Num_months,NaN,12,12,12,12,12,12,12,12,...,12,12,12,12,12,12,12,12,12,12
1,# Initial population,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,N_NF_t0,# Neonatal female,2070822,2070822,2070822,2070822,2070822,2070822,2070822,2070822,...,1805806,1805806,2803178,2803178,2803178,2803178,2070822,2070822,2070822,2070822
3,N_NM_t0,# Neonatal male,2070822,2070822,2070822,2070822,2070822,2070822,2070822,2070822,...,1212609,1212609,2586971,2586971,2586971,2586971,2070822,2070822,2070822,2070822
4,N_JF_t0,# Juvenile female,1915971,1915971,1915971,1915971,1915971,1915971,1915971,1915971,...,1525444,1525444,1508363,1508363,1508363,1508363,1915971,1915971,1915971,1915971
5,N_JM_t0,# Juvenile male,1147386,1147386,1147386,1147386,1147386,1147386,1147386,1147386,...,967746,967746,1146066,1146066,1146066,1146066,1147386,1147386,1147386,1147386
6,N_AF_t0,# Adult female,14049629,14049629,14049629,14049629,14049629,14049629,14049629,14049629,...,9293369,9293369,10864998,10864998,10864998,10864998,14049629,14049629,14049629,14049629
7,N_AM_t0,# Adult male,3048715,3048715,3048715,3048715,3048715,3048715,3048715,3048715,...,3390900,3390900,3055888,3055888,3055888,3055888,3048715,3048715,3048715,3048715
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,## Growth rate N -> J and J-> A,0.166667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
keys = df["AHLE Parameter"].tolist()
keys = list(map(str, keys))
keys

['Num_months',
 '# Initial population',
 'N_NF_t0',
 'N_NM_t0',
 'N_JF_t0',
 'N_JM_t0',
 'N_AF_t0',
 'N_AM_t0',
 'nan',
 '## Growth rate N -> J and J-> A',
 'Beta',
 'nan',
 '# Fertility',
 'part',
 'prolif',
 'nan',
 '# lactation',
 'prop_F_milked',
 'lac_duration',
 'avg_daily_yield_ltr',
 'milk_value_ltr',
 'nan',
 '# Offtake',
 '## Currently fixed, but, should this be dependant on new pop size, to keep pop size as it was at t0',
 '## offtake must = offtake + dif between NNFt0 etc and NJF current',
 'GammaF ',
 'GammaM ',
 'nan',
 '# Mortality ## informed from META analysis',
 'AlphaN',
 'AlphaJ',
 'AlphaF',
 'AlphaM',
 'nan',
 '# Culls',
 'CullF',
 'CullM',
 'nan',
 '## Production parameters (kg)',
 'nan',
 '# Liveweight conversion (kg) ## Informed from META analysis',
 'lwNF  ',
 'lwNM  ',
 'lwJF ',
 'lwJM ',
 'lwAF ',
 'lwAM ',
 'nan',
 '# carcase yeild',
 'ccy ',
 'nan',
 '## Financial value of live animals',
 '# Ethiopian Birr',
 'fvNF ',
 'fvJF ',
 'fvAF',
 'fvNM',
 'fvJM',
 'fvAM',
 'nan',
 '## Off take which go for fertility in females (used when calculating hide numbers)',
 '#fert_offtake',
 'nan',
 '## skin/hides  ',
 '## parameters can be updated through expert opinion but adding options for flexibility here',
 'hides_rate',
 'hides_rate_mor',
 'nan',
 '# 1 usd per piece = 51 eth birr',
 'hides_value',
 'nan',
 '# manure rate (kg produced/animal/day)',
 'Man_N',
 'Man_J',
 'Man_A',
 'nan',
 '# 0.0125 USD / kg = 0.65 eth birr per kg 2021 price',
 'Man_value',
 '  ',
 '## dry matter requirements as proportion of liveweight',
 'DM_req_prpn_NF',
 'DM_req_prpn_NM',
 'DM_req_prpn_JF',
 'DM_req_prpn_JM',
 'DM_req_prpn_AF',
 'DM_req_prpn_AM',
 'nan',
 '## Proportion of livestock keepers that spend any money on feed',
 '## NOTE Currently the same for all age*sex groups',
 'prpn_lskeepers_purch_feed',
 'nan',
 '## For those spending any money on feed, the proportion of feed that is purchased',
 '## NOTE Currently the same for all age*sex groups',
 'prpn_feed_paid_for',
 'nan',
 '## Input parameters ## just example distributions for now',
 'Feed_cost_kg',
 'nan',
 '## variable results for the amount of dry matter in wheat and barley and tef in Ethiopia',
 '## range 30-90%',
 '## taking 70% as an estimate for this trial',
 'DM_in_feed',
 'nan',
 '## Labour cost',
 '## birr/head/month',
 '## example code to change labour cost to selecting from distribution',
 'Lab_SR',
 'lab_non_health',
 'nan',
 '## Helath care costs',
 '## birr/head/month',
 '## this includes medicines and veterinary care',
 '## and changing health care costs to select from distribution',
 'Health_exp',
 'nan',
 '## Capital costs',
 '## for this we are using bank of Ethiopia inflation rate',
 'Interest_rate',
 'Infrastructure_per_head']

In [25]:
df_val = df.iloc[:,2:]

In [26]:
df_val.head()

,CLM_S_Current,CLM_S_Ideal,CLM_S_all_mortality_zero,CLM_S_all_mort_25_imp,CLM_S_all_mort_50_imp,CLM_S_all_mort_75_imp,CLM_S_mortality_zero_N,CLM_S_mortality_zero_J,CLM_S_mortality_zero_AF,CLM_S_mortality_zero_AM,...,Past_S_Current_growth_75_imp_All,Past_S_Current_growth_100_imp_All,CLM_G_Current_growth_25_imp_All,CLM_G_Current_growth_50_imp_All,CLM_G_Current_growth_75_imp_All,CLM_G_Current_growth_100_imp_All,CLM_S_Current_growth_25_imp_All,CLM_S_Current_growth_50_imp_All,CLM_S_Current_growth_75_imp_All,CLM_S_Current_growth_100_imp_All
0,12,12,12,12,12,12,12,12,12,12,...,12,12,12,12,12,12,12,12,12,12
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2070822,2070822,2070822,2070822,2070822,2070822,2070822,2070822,2070822,2070822,...,1805806,1805806,2803178,2803178,2803178,2803178,2070822,2070822,2070822,2070822
3,2070822,2070822,2070822,2070822,2070822,2070822,2070822,2070822,2070822,2070822,...,1212609,1212609,2586971,2586971,2586971,2586971,2070822,2070822,2070822,2070822
4,1915971,1915971,1915971,1915971,1915971,1915971,1915971,1915971,1915971,1915971,...,1525444,1525444,1508363,1508363,1508363,1508363,1915971,1915971,1915971,1915971

In [27]:
extras = '''
species: smallruminants
nruns: 10000
seed_value: NULL\n
'''

for (col_name, col_data) in df_val.items():
    print(col_name) # yaml file
    filename = "./smallruminants/temp_ruminants/" + col_name + ".yaml"
    file = open(filename, "a")
    header = f"##### {col_name} #####\n"
    file.write(header)
    file.write(extras)
    for idx, data in enumerate(col_data):
        line = ""
        if keys[idx].startswith("#"):
            line = keys[idx]
        elif keys[idx] == "nan" or keys[idx].isspace():
            line = ""
        else:
            val = str(data)
            if ("/" in str(data)) and ("(" not in str(data)):
                nums = str(data).split("/")
                val = str(float(nums[0]) / float(nums[1]))
            elif str(data) == "0.9/(12*4)":
                val = str(0.9 / (12 * 4))
            line = keys[idx] + ": " + val
        line = line + "\n"
        file.write(line)
        # print(line)
    file.close()

CLM_S_Current
CLM_S_Ideal
CLM_S_all_mortality_zero
CLM_S_all_mort_25_imp
CLM_S_all_mort_50_imp
CLM_S_all_mort_75_imp
 CLM_S_mortality_zero_N
 CLM_S_mortality_zero_J
 CLM_S_mortality_zero_AF
 CLM_S_mortality_zero_AM
CLM_S_mort_25_imp_N
CLM_S_mort_50_imp_N
CLM_S_mort_75_imp_N
CLM_S_mort_25_imp_J
CLM_S_mort_50_imp_J
CLM_S_mort_75_imp_J
CLM_S_mort_25_imp_AF
CLM_S_mort_50_imp_AF
CLM_S_mort_75_imp_AF
CLM_S_mort_25_imp_AM
CLM_S_mort_50_imp_AM
CLM_S_mort_75_imp_AM
CLM_S_ideal_NF
CLM_S_ideal_NM
CLM_S_ideal_JF
CLM_S_ideal_JM
CLM_S_ideal_AF
CLM_S_ideal_AM
CLM_G_Current
CLM_G_Ideal
CLM_G_all_mortality_zero
CLM_G_all_mort_25_imp
CLM_G_all_mort_50_imp
CLM_G_all_mort_75_imp
 CLM_G_mortality_zero_N
 CLM_G_mortality_zero_J
 CLM_G_mortality_zero_AF
 CLM_G_mortality_zero_AM
CLM_G_mort_25_imp_N
CLM_G_mort_50_imp_N
CLM_G_mort_75_imp_N
CLM_G_mort_25_imp_J
CLM_G_mort_50_imp_J
CLM_G_mort_75_imp_J
CLM_G_mort_25_imp_AF
CLM_G_mort_50_imp_AF
CLM_G_mort_75_imp_AF
CLM_G_mort_25_imp_AM
CLM_G_mort_50_imp_AM
CLM_G_mort_75_imp_AM
CLM_G_ideal_NF
CLM_G_ideal_NM
CLM_G_ideal_JF
CLM_G_ideal_JM
CLM_G_ideal_AF
CLM_G_ideal_AM
Past_S_Current
Past_S_Ideal
Past_S_all_mortality_zero
Past_S_all_mort_25_imp
Past_S_all_mort_50_imp
Past_S_all_mort_75_imp
 Past_S_mortality_zero_N
Past_S_mortality_zero_J
 Past_S_mortality_zero_AF
 Past_S_mortality_zero_AM
Past_S_mort_25_imp_N
Past_S_mort_50_imp_N
Past_S_mort_75_imp_N
Past_S_mort_25_imp_J
Past_S_mort_50_imp_J
Past_S_mort_75_imp_J
Past_S_mort_25_imp_AF
Past_S_mort_50_imp_AF
Past_S_mort_75_imp_AF
Past_S_mort_25_imp_AM
Past_S_mort_50_imp_AM
Past_S_mort_75_imp_AM
Past_S_ideal_NF
Past_S_ideal_NM
Past_S_ideal_JF
Past_S_ideal_JM
Past_S_ideal_AF
Past_S_ideal_AM
Past_G_Current
Past_G_Ideal
Past_G_all_mortality_zero
Past_G_all_mort_25_imp
Past_G_all_mort_50_imp
Past_G_all_mort_75_imp
Past_G_mortality_zero_N
Past_G_mortality_zero_J
Past_G_mortality_zero_AF
Past_G_mortality_zero_AM
Past_G_mort_25_imp_N
Past_G_mort_50_imp_N
Past_G_mort_75_imp_N
Past_G_mort_25_imp_J
Past_G_mort_50_imp_J
Past_G_mort_75_imp_J
Past_G_mort_25_imp_AF
Past_G_mort_50_imp_AF
Past_G_mort_75_imp_AF
Past_G_mort_25_imp_AM
Past_G_mort_50_imp_AM
Past_G_mort_75_imp_AM
Past_G_ideal_NF
Past_G_ideal_NM
Past_G_ideal_JF
Past_G_ideal_JM
Past_G_ideal_AF
Past_G_ideal_AM
CLM_S_Current_repro_25_imp
CLM_S_Current_repro_50_imp
CLM_S_Current_repro_75_imp
CLM_S_Current_repro_100_imp
CLM_G_Current_repro_25_imp
CLM_G_Current_repro_50_imp
CLM_G_Current_repro_75_imp
CLM_G_Current_repro_100_imp
Past_S_Current_repro_25_imp
Past_S_Current_repro_50_imp
Past_S_Current_repro_75_imp
Past_S_Current_repro_100_imp
Past_G_Current_repro_25_imp
Past_G_Current_repro_50_imp
Past_G_Current_repro_75_imp
Past_G_Current_repro_100_imp
CLM_S_Current_growth_25_imp_NF
CLM_S_Current_growth_25_imp_NM
CLM_S_Current_growth_25_imp_JF
CLM_S_Current_growth_25_imp_JM
CLM_S_Current_growth_25_imp_AF
CLM_S_Current_growth_25_imp_AM
CLM_S_Current_growth_50_imp_NF
CLM_S_Current_growth_50_imp_NM
CLM_S_Current_growth_50_imp_JF
CLM_S_Current_growth_50_imp_JM
CLM_S_Current_growth_50_imp_AF
CLM_S_Current_growth_50_imp_AM
CLM_S_Current_growth_75_imp_NF
CLM_S_Current_growth_75_imp_NM
CLM_S_Current_growth_75_imp_JF
CLM_S_Current_growth_75_imp_JM
CLM_S_Current_growth_75_imp_AF
CLM_S_Current_growth_75_imp_AM
CLM_S_Current_growth_100_imp_NF
CLM_S_Current_growth_100_imp_NM
CLM_S_Current_growth_100_imp_JF
CLM_S_Current_growth_100_imp_JM
CLM_S_Current_growth_100_imp_AF
CLM_S_Current_growth_100_imp_AM
CLM_G_Current_growth_25_imp_NF
CLM_G_Current_growth_25_imp_NM
CLM_G_Current_growth_25_imp_JF
CLM_G_Current_growth_25_imp_JM
CLM_G_Current_growth_25_imp_AF
CLM_G_Current_growth_25_imp_AM
CLM_G_Current_growth_50_imp_NF
CLM_G_Current_growth_50_imp_NM
CLM_G_Current_growth_50_imp_JF
CLM_G_Current_growth_50_imp_JM
CLM_G_Current_growth_50_imp_AF
CLM_G_Current_growth_50_imp_AM
CLM_G_Current_growth_75_imp_NF
CLM_G_Current_growth_75_imp_NM
CLM_G_Current_growth_75_imp_JF
CLM_G_Current_growth_75_imp_JM
CLM_G_Current_growth_75_imp_AF
CLM_G_Current_growth_75_imp_AM
CLM_G_Current_growth_100_imp_NF
CLM_G_Current_growth_100_imp_NM
CLM_G_Current_growth_100_imp_JF
CLM_G_Current_growth_100_imp_JM
CLM_G_Current_growth_100_imp_AF
CLM_G_Current_growth_100_imp_AM
Past_S_Current_growth_25_imp_NF
Past_S_Current_growth_25_imp_NM
Past_S_Current_growth_25_imp_JF
Past_S_Current_growth_25_imp_JM
Past_S_Current_growth_25_imp_AF
Past_S_Current_growth_25_imp_AM
Past_S_Current_growth_50_imp_NF
Past_S_Current_growth_50_imp_NM
Past_S_Current_growth_50_imp_JF
Past_S_Current_growth_50_imp_JM
Past_S_Current_growth_50_imp_AF
Past_S_Current_growth_50_imp_AM
Past_S_Current_growth_75_imp_NF
Past_S_Current_growth_75_imp_NM
Past_S_Current_growth_75_imp_JF
Past_S_Current_growth_75_imp_JM
Past_S_Current_growth_75_imp_AF
Past_S_Current_growth_75_imp_AM
Past_S_Current_growth_100_imp_NF
Past_S_Current_growth_100_imp_NM
Past_S_Current_growth_100_imp_JF
Past_S_Current_growth_100_imp_JM
Past_S_Current_growth_100_imp_AF
Past_S_Current_growth_100_imp_AM
Past_G_Current_growth_25_imp_NF
Past_G_Current_growth_25_imp_NM
Past_G_Current_growth_25_imp_JF
Past_G_Current_growth_25_imp_JM
Past_G_Current_growth_25_imp_AF
Past_G_Current_growth_25_imp_AM
Past_G_Current_growth_50_imp_NF
Past_G_Current_growth_50_imp_NM
Past_G_Current_growth_50_imp_JF
Past_G_Current_growth_50_imp_JM
Past_G_Current_growth_50_imp_AF
Past_G_Current_growth_50_imp_AM
Past_G_Current_growth_75_imp_NF
Past_G_Current_growth_75_imp_NM
Past_G_Current_growth_75_imp_JF
Past_G_Current_growth_75_imp_JM
Past_G_Current_growth_75_imp_AF
Past_G_Current_growth_75_imp_AM
Past_G_Current_growth_100_imp_NF
Past_G_Current_growth_100_imp_NM
Past_G_Current_growth_100_imp_JF
Past_G_Current_growth_100_imp_JM
Past_G_Current_growth_100_imp_AF
Past_G_Current_growth_100_imp_AM
Past_G_Current_growth_25_imp_All
Past_G_Current_growth_50_imp_All
Past_G_Current_growth_75_imp_All
Past_G_Current_growth_100_imp_All
Past_S_Current_growth_25_imp_All
Past_S_Current_growth_50_imp_All
Past_S_Current_growth_75_imp_All
Past_S_Current_growth_100_imp_All
CLM_G_Current_growth_25_imp_All
CLM_G_Current_growth_50_imp_All
CLM_G_Current_growth_75_imp_All
CLM_G_Current_growth_100_imp_All
CLM_S_Current_growth_25_imp_All
CLM_S_Current_growth_50_imp_All
CLM_S_Current_growth_75_imp_All
CLM_S_Current_growth_100_imp_All